### ISSUE TITLE
Support Visual Studio 2017

### ISSUE THREAD

**Issue by insane4sure** [thecoderok/quick-copy-vs#7]
Installing the current version produces a warning: "The following extensions are not compatible with Visual Studio 2017. Installation may cause Visual Studio to be unstable."

![image](https://user-images.githubusercontent.com/5393986/27431721-7de5cca6-571b-11e7-9c55-f48e848fa4c2.png)

**Comment by fireundubh** [comment]
Migrating the plugin to VS2017 is pretty straightforward.

1. Open the solution in VS2017.
2. Use NuGet to install: `Microsoft.VSSDK.BuildTools`
3. Use NuGet to install: `Dev15BinariesForRoslyn`
4. Right-click `source.extension.vsixmanifest` and add a new prerequisite: `Visual Studio core editor`.
5. Add new install targets: `Microsoft.VisualStudio.*`
6. Right-click the project and change the target framework to: `.NET Framework 4.6` or higher.
7. Add EnvDTE and EnvDTE80 references from `C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\PublicAssemblies\`.
7. Add missing interop references from `C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\PublicAssemblies\`.
7. Build.
